### PR TITLE
Rewrite to use proper python XML handlers

### PR DESCRIPTION
**Pull request by drewbroadley**
I've rewritten, and thinned it down a lot to use proper XML parsers/creation libraries.

### CODE REVIEW

**Comment by watzon** [comment]
This doesn't fix #1 right?

**Comment by drewbroadley** [comment]
It doesn't at the moment, but what it does is brings the creation of XML to internal libraries rather than creating the strings ourselves.

I'm down a rabbit hole on the whole collections.OrderedDict() thing and it requires some heavier thinking which I don't have right now.

I saw this as a first effort of contribution :)

**Comment by watzon** [comment]
@drewbroadley sounds great to me. If you could just remove the block

``` python
import ipdb;
ipdb.set_trace()
```

I'll get it merged in. Thanks for the help!

**Comment by drewbroadley** [comment]
Sorted 👍

**Pull request merged**
